name: climatenet
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - xarray
  - netcdf4
  - cartopy
  - pytorch
  - torchvision
  - pip
  - pip:
      - haversine
      - tensorflow-macos
      - tensorflow-metal